t/131: Contextual toolbar sample
ckeditor/ckeditor5-ui-default pull request #135
Opened 2016-12-07 13:32 UTC by oleq

It's a demo.

Depends on #98.

2016-12-07 18:58 UTC, Reinmar commented on tests/manual/createcontextualtoolbar/createcontextualtoolbar.js
> +		top: targetRect.bottom + 15,
What's 15?

2016-12-08 10:04 UTC, oleq commented on tests/manual/createcontextualtoolbar/createcontextualtoolbar.js
> +		top: targetRect.bottom + 15,
https://github.com/ckeditor/ckeditor5-ui-default/blob/t/131/src/balloonpanel/balloonpanelview.js#L19 I forgot to make these public. Static class properties?

2016-12-13 13:04 UTC, Reinmar requested changes
It doesn't work on Firefox at all. Apparently there's either no click event when selection is made or click is fired before the selection is made.

2016-12-13 13:04 UTC, Reinmar commented on src/balloonpanel/balloonpanelview.js
> +BalloonPanelView.arrowHorizontalOffset = arrowHorizontalOffset;
Why are you exposing these values if you're not reading it later on but use the consts? This means that if someone changes the theme and try to change these values it's not going to work.

2016-12-13 13:04 UTC, Reinmar commented on tests/manual/contextualtoolbar/contextualtoolbar.js
> +		name: 's'
I'm thinking now... how does this value affect anything? It certainly isn't used anywhere in this code. So perhaps it doesn't need to be defined at all? Am I right that only a feature which wants to understand which position the `getOptimalPosition` function had returned  needs to define it?

2016-12-13 13:04 UTC, Reinmar commented on tests/manual/contextualtoolbar/contextualtoolbar.js
> +		name: 's'
OK, I see that these values are also used in themes. So you should also update `BallonPanelView#position` values. Or even better – extract it to some typedef and document that it's related to the theme's classes.

2016-12-13 14:16 UTC, Reinmar commented
The same problem can be reproduced in Safari.

2016-12-16 09:41 UTC, oleq commented on tests/manual/contextualtoolbar/contextualtoolbar.js
> +		name: 's'
I'm not quite sure what you expect me to change. Positions are documented https://github.com/ckeditor/ckeditor5-utils/blob/master/src/dom/position.js#L263-L272. A position must have a name for any code using the `getOptimalPosition` utility to know, which of the positions have been chosen, not only what coordinates represent it. We've discussed it already.

2016-12-16 09:44 UTC, oleq commented
As for the Safari, the editor won't start in this browser and it has nothing to do with the scope of the PR. The question is: where's an issue for that?

2016-12-16 09:48 UTC, Reinmar commented
> As for the Safari, the editor won't start in this browser and it has nothing to do with the scope of the PR. The question is: where's an issue for that?

Update ckeditor5-dev-tests. It has been fixed.

2016-12-16 09:50 UTC, Reinmar commented on tests/manual/contextualtoolbar/contextualtoolbar.js
> +		name: 's'
What I'm expecting is that the set of supported names is defined somewhere. Initially I thought that this set is totally open, but it's not – the names must much the positions supported by the theme. So we should indicate (to help the developer understanding what it all is) that this is a set of 6 values *and* that you can add more if you style them.

2016-12-16 10:08 UTC, oleq commented
> Update ckeditor5-dev-tests. It has been fixed.

No improvement.

![image](https://cloud.githubusercontent.com/assets/1099479/21259024/e3fa22a6-c37f-11e6-974c-2e29075f2631.png)

2016-12-16 10:20 UTC, Reinmar commented
That's exactly the issue I fixed recently and it WFM:

![image](https://cloud.githubusercontent.com/assets/156149/21259409/8f212a84-c381-11e6-8bb3-6691109b2e65.png)


Make sure to update ckeditor5 before and then reinstall ckeditor5-dev-tests.

2016-12-16 10:21 UTC, Reinmar commented
That was the issue: https://github.com/ckeditor/ckeditor5-dev-tests/issues/40. And the code landed in 3.1.1.

2016-12-16 10:25 UTC, oleq commented
...and hasn't been updated on master

```
(master 1ea8f69) oleq@Aleksanders-MBP.local ~/CK/5/ckeditor5> grep ckeditor5-dev-tests package.json
    "@ckeditor/ckeditor5-dev-tests": "^3.1.0",
```

2016-12-16 10:37 UTC, Reinmar commented
> ...and hasn't been updated on master

^3.1.0 satisfies 3.1.1. So everything was up to date.

2016-12-16 10:39 UTC, oleq commented
So no idea then. Updated all packages, `npm i` and there's still that error.

2016-12-16 10:44 UTC, Reinmar commented
> So no idea then. Updated all packages, npm i and there's still that error.

I know – that's why `npm i` is useless. And `npm update` is unreliable, so I prefer to remove the packages which I want to update and just install them again.

2016-12-16 10:49 UTC, oleq commented
OK. Now I got it. It works in Safari. 

But the whole npm thing is weird, really. The problem will return sooner or later.

2016-12-16 10:51 UTC, Reinmar commented
> But the whole npm thing is weird, really. The problem will return sooner or later.

It returns every day. It's how npm works and either we learn how to live with it or quit or jobs ;P We can also consider Yarn, but it didn't work in our case previously.

2016-12-16 13:46 UTC, Reinmar commented
Toolbar should disappear when selection changes:

![dec-16-2016 14-43-31](https://cloud.githubusercontent.com/assets/156149/21264796/7318d7e8-c39e-11e6-825a-62e46ececcfc.gif)

2016-12-16 13:49 UTC, oleq commented
> Toolbar should disappear when selection changes:

This is but a sample, an entry point to actual implementation. There are still many behaviors that will need to be implemented, and this is just one of them. The sample should show the idea as simple as possible; it's up to actual integration to make it perfect. So I don't think this belongs to the scope of this PR.

2016-12-16 13:49 UTC, Reinmar commented
Hm... OK. Let's polish the behaviour in actual usage places.

2016-12-16 13:54 UTC, merged